"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "HectorMRC"
email = "thehector1593@gmail.com"

[ui]
editor = "nvim"

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"

[aliases]
a = ["abandon"]
d = ["describe"]
dff = ["diff", "-r"]
e = ["edit", "--ignore-immutable"]
f = ["git", "fetch", "--all-remotes"]
gp = ["git", "push"]
mm = ["b", "m", "main"]
mb = ["bookmark", "move", "--from", "closest_bookmark(@-)"]
n = ["new"]
sq = ["squash", "-u"]